// <auto-generated />
using System;
using Database.EfAppDbContextModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320050520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.EfAppDbContextModels.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Branches__3214EC07E489372B");

                    b.HasIndex(new[] { "MerchantId" }, "IX_Branches_MerchantId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.BranchInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__BranchIn__3214EC073EFA602C");

                    b.HasIndex(new[] { "BranchId" }, "IX_BranchInventory_BranchId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "ProductId" }, "IX_BranchInventory_ProductId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "BranchId", "ProductId" }, "UQ_BranchInventory_Branch_Product")
                        .IsUnique()
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("BranchInventory", (string)null);
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC072704BE8F");

                    b.HasIndex(new[] { "MerchantId" }, "IX_Categories_MerchantId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC071AE5326C");

                    b.HasIndex(new[] { "MerchantId" }, "IX_Customers_MerchantId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId", "Email" }, "IX_Customers_Merchant_Email")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId", "PhoneNumber" }, "IX_Customers_Merchant_Phone")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Merchant__3214EC07476D85FB");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07CAC59078");

                    b.HasIndex(new[] { "BranchId" }, "IX_Orders_BranchId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "BranchId", "OrderDate" }, "IX_Orders_Branch_Date")
                        .IsDescending(false, true)
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Orders_CustomerId");

                    b.HasIndex(new[] { "ProcessedById" }, "IX_Orders_ProcessedById");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC07297A9A80");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderItems_OrderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderItems_ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC07ECF3359B");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId" }, "IX_Products_MerchantId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId", "Name" }, "IX_Products_Merchant_Name")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId", "Sku" }, "UQ_Products_Merchant_SKU")
                        .IsUnique()
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ProductI__3214EC07A6EE7438");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductImages_ProductId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07C4E4BE91");

                    b.HasIndex(new[] { "BranchId" }, "IX_Users_BranchId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "MerchantId" }, "IX_Users_MerchantId")
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique()
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "Username" }, "UQ_Users_Username")
                        .IsUnique()
                        .HasFilter("([DeletedAt] IS NULL)");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E473704BEA")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105342B30EDB2")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Branch", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Merchant", "Merchant")
                        .WithMany("Branches")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Branches_Merchants");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.BranchInventory", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Branch", "Branch")
                        .WithMany("BranchInventories")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchInventory_Branches");

                    b.HasOne("Database.EfAppDbContextModels.Product", "Product")
                        .WithMany("BranchInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BranchInventory_Products");

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Category", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Merchant", "Merchant")
                        .WithMany("Categories")
                        .HasForeignKey("MerchantId")
                        .IsRequired()
                        .HasConstraintName("FK_Categories_Merchants");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Customer", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Merchant", "Merchant")
                        .WithMany("Customers")
                        .HasForeignKey("MerchantId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Merchants");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Order", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Branches");

                    b.HasOne("Database.EfAppDbContextModels.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("Database.EfAppDbContextModels.User", "ProcessedBy")
                        .WithMany("Orders")
                        .HasForeignKey("ProcessedById")
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.OrderItem", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.HasOne("Database.EfAppDbContextModels.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Product", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.HasOne("Database.EfAppDbContextModels.Merchant", "Merchant")
                        .WithMany("Products")
                        .HasForeignKey("MerchantId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Merchants");

                    b.Navigation("Category");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.ProductImage", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.User", b =>
                {
                    b.HasOne("Database.EfAppDbContextModels.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Users_Branches");

                    b.HasOne("Database.EfAppDbContextModels.Merchant", "Merchant")
                        .WithMany("Users")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("FK_Users_Merchants");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Branch", b =>
                {
                    b.Navigation("BranchInventories");

                    b.Navigation("Orders");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Merchant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Categories");

                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.Product", b =>
                {
                    b.Navigation("BranchInventories");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("Database.EfAppDbContextModels.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
